name: Build iOS IPA

on:
  push:
    branches:
      - main

jobs:
  build_ios:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.1'
          cache: true

      - name: Install Dart SDK
        run: dart --version

      - name: Install fastlane
        run: sudo gem install fastlane

      - name: Set MATCH_PASSWORD environment variable
        run: echo "MATCH_PASSWORD=${{ secrets.MATCH_PASSWORD }}" >> $GITHUB_ENV

      - name: Match certificates and provisioning profiles
        run: fastlane match development --git_url "https://github.com/Yutou0830/hello-github-actions.git"

      - name: Build iOS IPA
        run: |
          flutter pub get
          flutter build ipa --release

