name: Build iOS IPA

on:
  push:
    branches:
      - main

jobs:
  build_ios:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.1'
          cache: true
      - name: Install Dart SDK
        run: dart --version
      - name: Build IPA
        run: |
          flutter pub get
          flutter build ipa
